version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    #container_name: 'rabbitmq'
    ports:
        - 15672:15672
        - 5672:5672
    networks:
        - rabbitmq_go_net
  employee.api:
    image: ${DOCKER_REGISTRY-}employeeapi
    build:
      context: .
      dockerfile: Employee.API/Dockerfile
    depends_on:
      - rabbitmq 
    networks:
        - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge