version: '3.4'

services:
  employee.api:
    image: employeeapi:dev
    container_name: Employee.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Employee.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_employee.api$
    volumes:
      - D:\3G\Upscript\Microservices_New\Microservices\Template\Employee.API:/app
      - D:\3G\Upscript\Microservices_New\Microservices\Template:/src
      - C:\Users\hitesh.acharya\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_employee.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_employee.api$ \"/app/bin/Debug/net5.0/Employee.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true